---
all:
  children:
    database_servers:
      hosts:
        mysql01:
          ansible_host: 192.168.55.21
          ansible_user: tom
          ansible_ssh_private_key_file: /home/tom/.ssh/homelab_automation_ed25519
    secrets_servers:
      hosts:
        bao01:
          ansible_host: 192.168.55.24
          ansible_user: tom
          ansible_ssh_private_key_file: /home/tom/.ssh/homelab_automation_ed25519

    infrastructure_hosts:
      hosts:
        iza:
          ansible_connection: local
